---
- name: KDE Setup Playbook
  hosts: kde_host
  gather_facts: true
  become: false
  tasks:
    - name: KDE | Find User Home Directory
      set_fact:
        pv_kde_user_home_dir: "{{  ansible_facts.user_dir  }}"

    - name: KDE | Find User Config Directory
      set_fact:
        pv_kde_user_config_dir: "{{  pv_kde_user_home_dir  }}/.config"

    - name: KDE | Find User Share Directory
      set_fact:
        pv_kde_user_share_dir: "{{  pv_kde_user_home_dir  }}/.local/share"

    - name: KDE | Find User temp Directory
      set_fact:
        pv_kde_user_tmp_dir: "{{  pv_kde_user_home_dir  }}/.tmp/kde"

    - name: KDE | Create Directory
      ansible.builtin.file:
        state: directory
        path: "{{  item  }}"
        recurse: true
      with_items:
        - "{{  pv_kde_user_home_dir  }}"
        - "{{  pv_kde_user_share_dir  }}/themes"
        - "{{  pv_kde_user_share_dir  }}/plasma/desktoptheme/"
        - "{{  pv_kde_user_share_dir  }}/aurorae/themes"
        - "{{  pv_kde_user_share_dir  }}/color-schemes"
        - "{{  pv_kde_user_share_dir  }}/plasma/look-and-feel"
        - "{{  pv_kde_user_config_dir  }}/Kvantum"
        - "{{  pv_kde_user_tmp_dir  }}"
        #- "{{  pv_kde_user_tmp_dir  }}/Nordic-kde"
        #- "{{  pv_kde_user_tmp_dir  }}/Nordic"

    - name: Download Tasks
      import_tasks: tasks/download.yml
    - name: Settings Tasks
      import_tasks: tasks/settings.yml
