---
- name: KDE Setup Playbook
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: KDE | Find User Home Directory
      set_fact:
        pv_kde_user_home_dir: "{{  ansible_facts.user_dir  }}"

    - name: KDE | Find User Config Directory
      set_fact:
        pv_kde_user_config_dir: "{{  pv_kde_user_home_dir  }}/.config"

    - name: KDE | Find User Share Directory
      set_fact:
        pv_kde_user_share_dir: "{{  pv_kde_user_home_dir  }}/.local/share"

    - name: KDE | Find User temp Directory
      set_fact:
        pv_kde_user_tmp_dir: "{{  pv_kde_user_home_dir  }}/.tmp/kde"

    - name: KDE | Create Directory
      ansible.builtin.file:
        state: directory
        path: "{{  item  }}"
      with_items:
        - "{{  pv_kde_user_home_dir  }}"
        - "{{  pv_kde_user_share_dir  }}/../bin"
        - "{{  pv_kde_user_share_dir  }}/themes"
        - "{{  pv_kde_user_share_dir  }}/plasma/desktoptheme/"
        - "{{  pv_kde_user_share_dir  }}/aurorae/themes"
        - "{{  pv_kde_user_share_dir  }}/color-schemes"
        - "{{  pv_kde_user_share_dir  }}/plasma/look-and-feel"
        - "{{  pv_kde_user_config_dir  }}/Kvantum"
        - "{{  pv_kde_user_config_dir  }}/konsave"
        - "{{  pv_kde_user_tmp_dir  }}"
        #- "{{  pv_kde_user_share_dir  }}/icons/candy-icons"
        #- "{{  pv_kde_user_tmp_dir  }}/Nordic-kde"
        #- "{{  pv_kde_user_tmp_dir  }}/Nordic"

    - name: KDE | Get System Python executable
      shell: $(readlink -f $(which python3)) -m pip install konsave --user --upgrade
      args:
        executable: /bin/bash

    - name: KDE | Copy Consave config
      ansible.builtin.copy:
        src: "files/konsave/"
        dest: "{{  pv_kde_user_config_dir  }}/konsave/"
        remote_src: false

    - name: KDE | Konsave Backup
      shell: "{{  pv_kde_user_share_dir  }}/../bin/konsave -s make-my-computer-backup-{{  ansible_date_time.epoch  }}"

    - name: Download Tasks
      import_tasks: tasks/download.yml
