- name: KDE | Settings | Set flip task switch
  community.general.ini_file:
    path: "{{  pv_kde_user_config_dir  }}/kwinrc"
    no_extra_spaces: true
    section: TabBox
    option: LayoutName
    value: flipswitch

- name: KDE | Kwin | Virtual Desktop
  community.general.ini_file:
    path: "{{  pv_kde_user_config_dir  }}/kwinrc"
    no_extra_spaces: true
    section: Desktops
    option: "{{  item.option  }}"
    value: "{{  item.value  }}"
  with_items:
    - {option: Name_1, value: Primary}
    - {option: Name_2, value: Secondary}
    - {option: Number, value: 2}
    - {option: Rows, value: 2}

- name: KDE | Kwin | Plugins
  community.general.ini_file:
    path: "{{  pv_kde_user_config_dir  }}/kwinrc"
    no_extra_spaces: true
    section: Plugins
    option: "{{  item  }}"
    value: 'true'
  with_items:
    - diminactiveEnabled
    - slidebackEnabled
    - blurEnabled

- name: KDE | Kwin | Plugins Effect-Blur
  community.general.ini_file:
    path: "{{  pv_kde_user_config_dir  }}/kwinrc"
    no_extra_spaces: true
    section: Effect-Blur
    option: "{{  item.option  }}"
    value: "{{  item.value  }}"
  with_items:
    - {option: BlurStrength, value: 10}
    - {option: NoiseStrength, value: 10}

#######

- name: KDE | Kwin | Plugins with 3d
  community.general.ini_file:
    path: "{{  pv_kde_user_config_dir  }}/kwinrc"
    no_extra_spaces: true
    section: Plugins
    option: "{{  item  }}"
    value: 'true'
  with_items:
    - kwin4_effect_squashEnabled
    - magiclampEnabled
    - kwin4_effect_dimscreenEnabled
    - wobblywindowsEnabled
    - fallapartEnabled
